name: to_do_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.2
  time_picker_spinner: ^0.0.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  icons_flutter: ^0.0.4
  
  

flutter:
  assets:
    - asset/intro/onbording/
    - asset/intro/
    - asset/Login_Ragister/
    - asset/Home/
    

  uses-material-design: true

  
